import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Provider } from "@/components/provider";
import { Navbar } from "@/components/nav";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session
}: Readonly<{
  children: React.ReactNode;
  session: any;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased`}
      >
        <Provider session={session}>
          <Navbar />
        {children}
        </Provider>
      </body>
    </html>
  );
}
